# Generated by Django 4.2.19 on 2025-02-20 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='away_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_score',
        ),
    ]
