# Generated by Django 4.2.17 on 2025-02-08 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='confirmed',
            new_name='extra_time',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='opponent_score',
            new_name='away_score',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='score',
            new_name='home_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2',
        ),
        migrations.AddField(
            model_name='match',
            name='away_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='penalties',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('GROUP', 'Group Stage'), ('RO16', 'Round of 16'), ('QUARTER', 'Quarter Final'), ('SEMI', 'Semi Final'), ('FINAL', 'Final')], default='GROUP', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('DISPUTED', 'Disputed')], default='SCHEDULED', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='team_away',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='tournament.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='tournament.team'),
        ),
        migrations.AddField(
            model_name='result',
            name='extra_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='result',
            name='penalties',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='result',
            name='submitted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='result',
            name='submitting_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.team'),
        ),
        migrations.AlterField(
            model_name='result',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tournament.match'),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('match', 'submitting_team')},
        ),
        migrations.RemoveField(
            model_name='result',
            name='score_img',
        ),
        migrations.RemoveField(
            model_name='result',
            name='team',
        ),
    ]
