# Generated by Django 4.2.17 on 2025-02-11 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_rename_confirmed_match_extra_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='team',
            name='email',
        ),
    ]
