# Generated by Django 4.2.17 on 2025-02-16 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_alter_result_unique_together_match_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='registration_code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='strength_rating',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
