# Generated by Django 4.2.17 on 2025-02-16 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tournament.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0009_team_registration_code_team_strength_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='registration_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(default=tournament.models.get_admin_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='registration_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
